name: Terraform Destroy with Issue Comment

on: issue_comment

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VERSION: 0.12.29
    defaults:
      run:
        working-directory: main/kubernetes
    # strategy:
    #   matrix:
    #     workspace:
    #       - default
    #       # - prod
    #       # - staging

    steps:
      - name: Check if comment is destroy
        uses: rytswd/comvent@v0.1.0 # This line would pull down the release version of comvent
        id: comvent-destroy-all # Add an ID, so that you can control your step later
        with:
          keyword: "/terraform-destroy-all" # This is the regex string to search in the comment

      #* ---------------------------------------------------------------------- *#

      - uses: actions/checkout@v2
        if: steps.comvent-destroy-all.outputs.comvent != ''
      - uses: hashicorp/setup-terraform@v1
        if: steps.comvent-destroy-all.outputs.comvent != ''
        with:
          terraform_version: ${{ env.TF_VERSION }}
          cli_config_credentials_token: ${{ secrets.TERRAFORM_CLOUD_INIT_API_TOKEN }}
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        if: steps.comvent-destroy-all.outputs.comvent != ''
        with:
          version: "latest"
          project_id: rytswd-get-multi-cloud-k8s-v01
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Terraform Init
        if: steps.comvent-destroy-all.outputs.comvent != ''
        # env:
        #   TF_WORKSPACE: ${{ matrix.workspace }}
        run: terraform init

      - name: Terraform Destroy
        if: steps.comvent-destroy-all.outputs.comvent != ''
        # env:
        #   TF_WORKSPACE: ${{ matrix.workspace }}
        run: terraform destroy
