name: Terraform Destroy with Issue Comment

on:
  schedule:
    - cron: "0 0 * * *" # Every day midnight

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VERSION: 0.12.29
    defaults:
      run:
        working-directory: main/kubernetes
    # strategy:
    #   matrix:
    #     workspace:
    #       - default
    #       # - prod
    #       # - staging

    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TF_VERSION }}
          cli_config_credentials_token: ${{ secrets.TERRAFORM_CLOUD_INIT_API_TOKEN }}
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "latest"
          project_id: rytswd-get-multi-cloud-k8s-v01
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Terraform Init
        # env:
        #   TF_WORKSPACE: ${{ matrix.workspace }}
        run: terraform init

      - name: Terraform Destroy
        # env:
        #   TF_WORKSPACE: ${{ matrix.workspace }}
        run: terraform destroy -auto-approve
